name: push-next

on:
  push:
    branches: [next]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: 🚧 Build
        run: bun run build
      - name: 🔢 Custom Version
        run: npm version 0.0.0-next-${{ github.sha }} --git-tag-version false
      - name: 🚀 Publish next tag
        uses: JS-DevTools/npm-publish@v1
        with:
          tag: next
          token: ${{ secrets.NPM_TOKEN }}
